"""The backdrop library: named grounds the recording sits on.

A backdrop is one flat plate behind the inset video, so the only thing a "background"
has to describe is how to fill a W x H rectangle. Two kinds cover everything the design
asks for -- a solid, and a linear gradient -- and both are generated by ffmpeg source
filters, which is what lets `render._backdrop` treat them as interchangeable.

THREE CONSTRAINTS COME FROM `gradients`, NOT FROM TASTE:

* It rotates. `speed` defaults to 0.01 radians per FRAME and the filter turns its
  gradient line about the frame centre every frame, so the backdrop that shipped was
  slowly spinning: measured at 64x64/30fps on a black-to-white diagonal, the top-left
  pixel walked 0x00 -> 0x0d and the bottom-right 0xff -> 0xf3 over 45 frames. Every
  gradient here is emitted with `speed=0`.
* Stops are evenly spaced. There are up to eight colours (`c0`..`c7`, `nb_colors`) and
  no way to say "70% of the way along", so a design that wants a stop off-centre has to
  express it as an extra colour rather than a position. That is why `Background.colors`
  is a plain sequence with no offsets: a position field would be a lie.
* The gradient line must lie INSIDE the frame it is generated on. Any endpoint outside
  `[0, size-1]` is quietly replaced with a random one -- the filter's test for "the
  caller did not specify this" is `v < 0 || v >= size`, and the seed defaults to random
  -- so the backdrop that shipped, `x0=0:y0=0:x1=W:y1=H`, drew a DIFFERENT gradient on
  every render: six runs of the same command gave six different frames, against one
  distinct frame in six once `x1`/`y1` came down to `W-1`/`H-1`. See `gradient_plan`.

ANGLES ARE CSS ANGLES: degrees clockwise from "up", so 180 is a plain top-to-bottom
fade. The design spec writes its own canvas token as `linear-gradient(150deg, #1d1a17,
#121316)`, and matching that convention means a value from the spec, from a browser, or
from a designer's eyedropper can be typed in here without being reinterpreted.

The catalogue is a set of good defaults, not a jail: `BackdropSettings.background` may
also be `CUSTOM`, which means "use the colour the user picked".
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover -- project imports THIS module; see BackdropSettings
    from .geometry import Canvas
    from .project import BackdropSettings

# The sentinel `BackdropSettings.background` carries when the user picked their own
# colour instead of a swatch. Not a catalogue id, and asserted not to collide with one.
CUSTOM = "custom"

SOLID = "solid"
GRADIENT = "gradient"

# `gradients` exposes c0..c7 and refuses nb_colors outside 2..8.
MAX_STOPS = 8

_HEX = re.compile(r"^#[0-9a-fA-F]{6}$")


def is_color(value: object) -> bool:
    """True for the one colour syntax the whole product uses, `#rrggbb`.

    Deliberately narrower than ffmpeg's colour parser, which would also take names,
    `0x` prefixes and an `@alpha` suffix. The backdrop is the bottom of the composite,
    so an alpha there is meaningless, and a named colour would not survive the round
    trip through a QML colour picker that only ever emits hex.
    """
    return isinstance(value, str) and bool(_HEX.match(value))


@dataclass(frozen=True)
class Background:
    """One entry in the library, or the resolved form of a custom colour."""

    id: str
    name: str
    kind: str  # SOLID | GRADIENT
    colors: tuple[str, ...]
    # CSS degrees; ignored by solids. See the module docstring.
    angle: float = 0.0

    @property
    def is_gradient(self) -> bool:
        return self.kind == GRADIENT

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "kind": self.kind,
            "colors": list(self.colors),
            "angle": self.angle,
        }


def _solid(bg_id: str, name: str, color: str) -> Background:
    return Background(bg_id, name, SOLID, (color,))


def _gradient(bg_id: str, name: str, angle: float, *colors: str) -> Background:
    return Background(bg_id, name, GRADIENT, tuple(colors), angle)


# --- the library ------------------------------------------------------------
#
# Chosen against this product's palette (docs/design/spec.md 1 Tokens), not against a
# colour wheel. The rules that produced this list:
#
# * The greys are warm-shifted, like the spec's chrome greys, because the recording
#   itself supplies the neutral and a cold grey plate makes a warm UI screenshot look
#   yellowed. `slate` and `basalt` are the only cool ones and they are cool on purpose,
#   for footage that is itself warm.
# * The saturated tones are DARK and desaturated to roughly a sixth of full chroma. A
#   backdrop is 90% of the frame's area at the default 4% padding; anything with real
#   chroma at that size stops being a ground and starts competing with the video.
# * `bone`, `fog` and `sandstone` are the light end, for footage captured on a light
#   theme, where a near-black plate reads as a burnt-in letterbox.
# * The amber accent appears nowhere as a fill. It is the product's action colour --
#   spec 1: "every other important thing is amber" -- and a whole amber backdrop would
#   make every accented control disappear into it. `ember` and `terracotta` are as close
#   as the library gets, and both are browns.

_SOLIDS: tuple[Background, ...] = (
    _solid("ink", "Ink", "#0d0e10"),
    _solid("graphite", "Graphite", "#1b1d24"),
    _solid("slate", "Slate", "#2b303a"),
    _solid("clay", "Clay", "#3a322c"),
    _solid("espresso", "Espresso", "#241a14"),
    _solid("oxblood", "Oxblood", "#2e1418"),
    _solid("pine", "Pine", "#14211c"),
    _solid("abyss", "Abyss", "#10222b"),
    _solid("indigo", "Indigo", "#171a2e"),
    _solid("bone", "Bone", "#e9e5de"),
)

_GRADIENTS: tuple[Background, ...] = (
    # Literally the spec's `canvas` token. Selecting it makes the exported backdrop the
    # same surface the editor draws the recording on, which is the one case where the
    # preview and the finished file are supposed to be indistinguishable.
    _gradient("canvas", "Canvas", 150, "#1d1a17", "#121316"),
    _gradient("dusk", "Dusk", 160, "#232838", "#0f1016"),
    # Three stops: two-stop dark gradients band visibly across a 1080-pixel run, and a
    # midpoint that is not the arithmetic mean of the ends is the only fix available --
    # `gradients` cannot place a stop, so the mid colour has to BE a stop.
    _gradient("nocturne", "Nocturne", 165, "#1d2440", "#141726", "#0b0c12"),
    _gradient("ember", "Ember", 150, "#33200f", "#14100f"),
    _gradient("terracotta", "Terracotta", 145, "#3d241a", "#171113"),
    _gradient("moss", "Moss", 155, "#17251f", "#0d1211"),
    _gradient("harbour", "Harbour", 160, "#16262b", "#0d1115"),
    _gradient("basalt", "Basalt", 180, "#2c2f35", "#15171b"),
    _gradient("fog", "Fog", 170, "#dcd8d1", "#b4b0a9"),
    _gradient("sandstone", "Sandstone", 150, "#eae1d3", "#cabda6"),
)

CATALOG: tuple[Background, ...] = _SOLIDS + _GRADIENTS

_BY_ID: dict[str, Background] = {b.id: b for b in CATALOG}

# Cheap enough to run at import and it fails the whole test suite rather than one test:
# a duplicate id would make the swatch grid select two tiles at once, and `CUSTOM`
# colliding with an entry would make the colour picker unreachable.
assert len(_BY_ID) == len(CATALOG), "duplicate background id"
assert CUSTOM not in _BY_ID, f"{CUSTOM!r} is reserved for the user's own colour"


def find(bg_id: str) -> Background | None:
    """The entry, or None. Callers decide whether an unknown id is fatal -- loading a
    project it is not, clicking a swatch it is."""
    return _BY_ID.get(bg_id)


def catalog() -> list[dict]:
    """The whole library, JSON-ready, in display order: solids then gradients."""
    return [b.to_dict() for b in CATALOG]


def resolve(bd: "BackdropSettings", canvas: "Canvas") -> Background:
    """The Background a BackdropSettings actually means.

    `canvas` is needed for exactly one case and it is a compatibility case: a custom
    gradient predates the angle field, and what it drew was the corner-to-corner line
    `x0=0:y0=0:x1=W:y1=H`. That is a CSS angle only for one aspect ratio, so it is
    computed per canvas rather than frozen at 135 -- which would rotate every backdrop
    already sitting in someone's edit.json by 15.6 degrees at 16:9.
    """
    if bd.background != CUSTOM:
        entry = find(bd.background)
        if entry is not None:
            return entry
    if bd.gradient:
        return Background(
            CUSTOM, "Custom", GRADIENT, (bd.color, bd.gradient),
            diagonal_angle(canvas.width, canvas.height),
        )
    return Background(CUSTOM, "Custom", SOLID, (bd.color,))


def pad_colour(bd: "BackdropSettings") -> str:
    """One flat colour for the head/tail pads, as an ffmpeg colour string.

    The backdrop's own colour, so a card that does not fill the frame sits on the same
    ground the recording does rather than on a black band nothing else in the project
    uses. A gradient collapses to its first stop: tpad takes one colour, and the pad is
    behind a card rather than a surface in its own right.

    The default is the backdrop's default colour rather than black for the same reason
    -- it is what the rest of the project would have drawn there.
    """
    colour = (bd.color or "").strip()
    if not is_color(colour):
        return DEFAULT_PAD_COLOUR
    # ffmpeg takes 0xRRGGBB; the project stores CSS hex.
    return "0x" + colour.lstrip("#")


# The backdrop's own default, so an untouched project pads with the colour it would
# have used behind a backdrop rather than with a black nobody chose.
DEFAULT_PAD_COLOUR = "0x1b1d24"


# --- gradient geometry ------------------------------------------------------


def diagonal_angle(w: int, h: int) -> float:
    """The CSS angle whose gradient line runs exactly corner to corner on a w x h box.

    Verifiable from `gradient_line`: at this angle it returns (0, 0, w, h).
    """
    return math.degrees(math.atan2(w, -h)) % 360.0


def gradient_line(angle: float, w: int, h: int) -> tuple[float, float, float, float]:
    """The CSS gradient line for `angle` across a w x h box, in box pixels.

    The line is centred on the box and long enough that the perpendicular through each
    corner meets it inside its own length -- `L = |w sin| + |h cos|`, the standard CSS
    construction. That length is the whole reason to do this rather than just aiming the
    line at two corners: it is what makes the first and last colour land exactly ON the
    two extreme corners instead of being clipped somewhere inside the frame.

    Endpoints are floats and routinely NEGATIVE for any angle off the box diagonal.
    Returned that way on purpose: this is also the line a QML `Canvas` gradient wants,
    and it accepts coordinates outside the item.
    """
    rad = math.radians(angle)
    # y grows downward in both ffmpeg and QML, so "up" is -y and the CSS direction
    # vector (sin, cos) picks up a sign on its second component.
    dx, dy = math.sin(rad), -math.cos(rad)
    length = abs(w * dx) + abs(h * dy)
    cx, cy = w / 2.0, h / 2.0
    return (
        cx - dx * length / 2.0,
        cy - dy * length / 2.0,
        cx + dx * length / 2.0,
        cy + dy * length / 2.0,
    )


@dataclass(frozen=True)
class GradientPlan:
    """A `gradients` source whose line it will not throw away, plus the crop back.

    `gradients` treats any endpoint outside `[0, size-1]` as "unset" and substitutes a
    random one, and the CSS gradient line for anything but the box's own diagonal runs
    off at least one edge. So the source is generated on a frame grown until the whole
    line fits, with the line translated by `pad_x`/`pad_y` to clear the near edges, and
    the requested box cropped back out of it. What lands in the crop is exactly the
    gradient that was asked for: translating both the line and the sampling grid by the
    same vector cancels, and growing the far side adds pixels nobody keeps.

    Growth peaks near 150 degrees on 16:9 -- the vertical extent of the line maxes at
    540 + hypot(960, 540) = 1641 rows for a 1080-row box -- so a 1920x1080 gradient is
    generated at 1920x1643 and costs 1.6 ms a frame against 1.0 ms ungrown. Straight
    horizontal and vertical fades grow by a single pixel; the box diagonal, not at all.
    """

    # The frame the source is generated on, and the line on it.
    width: int
    height: int
    x0: int
    y0: int
    x1: int
    y1: int
    # The box that was actually asked for, and where it sits in that frame.
    box_width: int
    box_height: int
    pad_x: int
    pad_y: int

    @property
    def crop(self) -> tuple[int, int, int, int] | None:
        """`crop` arguments (w, h, x, y), or None when the frame is already the box.

        Keyed on the SIZE and not on the padding: a straight top-to-bottom fade needs no
        translation but still grows a row, because its far endpoint would otherwise sit
        at exactly `h` and be randomized away.
        """
        if (self.width, self.height) == (self.box_width, self.box_height):
            return None
        return (self.box_width, self.box_height, self.pad_x, self.pad_y)


def gradient_plan(angle: float, w: int, h: int) -> GradientPlan:
    """Turn a CSS angle into arguments `gradients` accepts. See GradientPlan."""
    # Rounded BEFORE the padding is measured, not after. `gradient_line` goes through
    # sin/cos, so a line that is exactly axis-aligned comes back with an endpoint at
    # -1.1e-13 -- and padding by the ceiling of that would grow every 180-degree
    # gradient by a pointless row and shift it a pixel off centre.
    x0, y0, x1, y1 = (round(v) for v in gradient_line(angle, w, h))
    pad_x = max(0, -min(x0, x1))
    pad_y = max(0, -min(y0, y1))
    x0, x1 = x0 + pad_x, x1 + pad_x
    y0, y1 = y0 + pad_y, y1 + pad_y
    return GradientPlan(
        # Wide enough for the box at its offset AND for the far endpoint, which must be
        # a valid pixel index rather than one past the end.
        width=max(w + pad_x, max(x0, x1) + 1),
        height=max(h + pad_y, max(y0, y1) + 1),
        x0=x0, y0=y0, x1=x1, y1=y1,
        box_width=w,
        box_height=h,
        pad_x=pad_x,
        pad_y=pad_y,
    )
